sudo: false
language: python

python:
  - "3.4"

install:
  - pip install -r test-requirements.txt

script:
 - nosetests --with-coverage --cover-package=storm -v

after_success:
 - coveralls

notifications:
  email: false
