sudo: false
language: python

python:
  - "3.4"

before_install:
  - pip install coveralls coverage pyparsing

install:
  - pip install -e . -r test-requirements.txt

script:
 - coverage run -m unittest discover --start-directory test
 - coverage report -m

after_success:
 - coveralls

notifications:
  email: false
